#-------------------------------
# General Site Settings
title: Yale Web
logo: logo.jpg # You can add own logo.
description: Contents About Web Dev


#-------------------------------
# Author Settings
author:
  name: Yale
  image: 01.jpg
  say-hello: Hello, Iâ€™m <strong>Yale</strong>
  bio: Talks, and writes about <strong>web</strong>, <strong>golang</strong>, <strong>react</strong>, and dev. I share tutorials, articles and researches. Loves <a href="#">coding</a> & share something interesting.


#-------------------------------
# Contact links
youtube: https://www.youtube.com/@yalecode918
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
